# 複数行コメント
[[plugins]]
    repo = 'tyru/caw.vim'

# カッコなどをいい感じに入れる(https://github.com/tpope/vim-surround)
[[plugins]]
    repo = 'tpope/vim-surround'

# ペアとなるカッコなどを追加、削除(https://github.com/jiangmiao/auto-pairs)
[[plugins]]
    repo = 'jiangmiao/auto-pairs'

# =などを揃える
[[plugins]]
    repo = 'junegunn/vim-easy-align'

# gitを編集履歴を左側に表示する
[[plugins]]
    repo = 'airblade/vim-gitgutter'

# gitでvimを使いやすくする
[[plugins]]
    repo = 'tpope/vim-fugitive'

# 非同期通信 (https://github.com/Shougo/vimproc.vim)
[[plugins]]
    repo = 'Shougo/vimproc.vim'

# フォルダを開きやすくする
[[plugins]]
    repo = 'preservim/nerdtree'
 
######## ステータスバーをいい感じにする
# ステータスバーをいい感じにする(https://github.com/vim-airline/vim-airline)
[[plugins]]
    repo = 'vim-airline/vim-airline'
    build = 'make'

# airlineとセットで入れる,themes(https://github.com/vim-airline/vim-airline-themes)
[[plugins]]
    repo = 'vim-airline/vim-airline-themes'

[[plugins]]
    repo = 'nanotech/jellybeans.vim'

# cpp c のコード整形(https://github.com/rhysd/vim-clang-format)
# Requirements 
# apt-get install clang-format
# vim-operator-user(highly recommended)
# vimproc.vim(recommended in Windows)
[[plugins]]
    repo = 'rhysd/vim-clang-format'
    on_ft = ['c','cpp']

# (https://github.com/kana/vim-operator-user)
[[plugins]]
    repo = 'kana/vim-operator-user'

######## 補完機能を実現するためのプラグイン
# vim-lspをつなげる
# [[plugins]]
    # repo = 'lighttiger2505/deoplete-vim-lsp'

# Language Server Protocolの実装
[[plugins]]
    repo = 'prabirshrestha/vim-lsp'
    hook_add = '''
    let g:lsp_log_file = ''
    let g:lsp_log_verbose = 1
    let g:lsp_diagnostics_enabled = 0
    '''

# Auto conplete
[[plugins]]
    repo = 'prabirshrestha/asyncomplete.vim'

# LSPのsupport
[[plugins]]
    repo = 'prabirshrestha/asyncomplete-lsp.vim'

# vim-lspの依存プラグイン(https://github.com/mattn/vim-lsp-settings)
[[plugins]]
    repo = 'mattn/vim-lsp-settings'
 
[[plugins]]
    repo = 'prabirshrestha/async.vim'

# vim-lsp-settingsの依存プラグイン
[[plugins]]
    repo = 'roxma/vim-hug-neovim-rpc'

# vim-lsp-settingsの依存プラグイン
[[plugins]]
    repo = 'roxma/nvim-yarp'

